import type { EventCardData } from "@/components/events/event-card";

export const demoEvents: EventCardData[] = [
  {
    id: "lille-jazz-table",
    title: "Jazz, vinyles et planches",
    description: "Une soirée posée autour de Blue Note, petites assiettes et discussions simples.",
    image: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1400&q=80",
    vibe: "Jazz",
    type: "vibplus",
    city: "Lille Centre",
    dateLabel: "Vendredi · 20:30",
    participants: 4,
    maxParticipants: 8,
    contributionAmount: 5,
  },
  {
    id: "wazemmes-boardgames",
    title: "Jeux de société chill",
    description: "Table ouverte pour découvrir des jeux modernes, sans esprit compétition.",
    image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=1400&q=80",
    vibe: "Jeux",
    type: "vib",
    city: "Wazemmes",
    dateLabel: "Samedi · 19:00",
    participants: 3,
    maxParticipants: 6,
    contributionAmount: 0,
  },
  {
    id: "roubaix-gaming",
    title: "Gaming coop et pizzas",
    description: "Canapé, jeux coop, zéro jugement sur le niveau et playlist maison.",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1400&q=80",
    vibe: "Gaming",
    type: "vibplus",
    city: "Roubaix",
    dateLabel: "Dimanche · 18:30",
    participants: 2,
    maxParticipants: 5,
    contributionAmount: 7,
  },
];
